vich_uploader:
    db_driver: orm

    mappings:
            image:
                uri_prefix: /images/products
                upload_destination: '%kernel.project_dir%/public/images/products'
                namer:
                  service: vich_uploader.namer_origname

